# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "fantasy42"
repo = "cryptovalid"

[changelog]
header = ""
body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## Unreleased
{% endif -%}

{% set remote_url = "https://github.com/" ~ remote.github.owner ~ "/" ~ remote.github.repo -%}

{% set group_order = [
  "🚀 Features",
  "🐛 Bug Fixes",
  "⚡ Performance",
  "🔨 Refactor",
  "🧪 Testing",
  "📚 Documentation",
  "🎨 Styling",
  "⚙️ Miscellaneous",
  "📦 Dependencies",
  "📝 Other Changes"
] -%}

{% for desired_group in group_order -%}
  {% set_global group_commits = [] -%}
  {% for commit in commits -%}
    {% if commit.group == desired_group -%}
      {% set_global group_commits = group_commits | concat(with=[commit]) -%}
    {% endif -%}
  {% endfor -%}
  {% if group_commits | length > 0 -%}
### {{ desired_group }}
{% for commit in group_commits -%}
- {% if commit.scope %}*({{ commit.scope }})* {% endif -%}{{ commit.message | upper_first }} - ([{{ commit.id | truncate(length=7, end="") }}]({{ remote_url }}/commit/{{ commit.id }})){% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}]({{ remote_url }}/pull/{{ commit.remote.pr_number }})){% endif %}
{% endfor %}

  {% endif -%}
{% endfor -%}

{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 -%}
  ## New Contributors
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) -%}
- @{{ contributor.username }} made their first contribution{% if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ remote_url }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{% endif %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_preprocessors = [
  { pattern = '\nCo-authored-by:.*', replace = "", replace_all = true },
  { pattern = '\s*\(#\d+\)', replace = "", replace_all = true },
  { pattern = '\s+$', replace = "" },
]

commit_parsers = [
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^refactor", group = "🔨 Refactor" },
  { message = "^docs", group = "📚 Documentation" },
  { message = "^style", group = "🎨 Styling" },
  { message = "^test", group = "🧪 Testing" },
  { message = "^chore\\(deps\\)", group = "📦 Dependencies" },
  { message = "^Bump version to", skip = true },
  { message = "^Merge (pull request|branch)", skip = true },
  { message = "^(chore|ci|build)", group = "⚙️ Miscellaneous" },
  { message = ".*", group = "📝 Other Changes" },
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"
